### ISSUE TITLE
how to get started

### ISSUE THREAD

**Issue by Amazingmum** [govvijaycal/mkz_mpc_path_follower#1]
so how can i get started with the raw package from the dbw_mkz. How to drive the car and steer

**Comment by govvijaycal** [comment]
First, you can set up the dbw_mkz_simulation package here: https://bitbucket.org/DataspeedInc/dbw_mkz_simulation/src/default/

If you run the launch files for the lane keep demo (see the documentation at the above link), then it will run a PID/lookahead point based control for acceleration and steering.  You can use rqt_graph to see the topics/nodes which are responsible for control and replace them with your own code.

**Comment by Amazingmum** [comment]
Thank you very much.


I feel a little hard at the school to learn this knowledge myself. Here are some introductory tutorials, such as how to build your own vehicle model, especially the chassis model with Ackermann steering, how to write the code to drive the vehicle, how to build traffic scenarios such as roads.


I have been looking for a tutorial on the Internet for a long time, I hope to get guidance from professionals.




------------------ 原始邮件 ------------------
发件人: "Vijay Govindarajan"<notifications@github.com>; 
发送时间: 2019年5月4日(星期六) 凌晨1:37
收件人: "govvijaycal/mkz_mpc_path_follower"<mkz_mpc_path_follower@noreply.github.com>; 
抄送: "657186830"<657186830@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [govvijaycal/mkz_mpc_path_follower] how to get started (#1)




First, you can set up the dbw_mkz_simulation package here: https://bitbucket.org/DataspeedInc/dbw_mkz_simulation/src/default/
 
If you run the launch files for the lane keep demo (see the documentation at the above link), then it will run a PID/lookahead point based control for acceleration and steering.  You can use rqt_graph to see the topics/nodes which are responsible for control and replace them with your own code.
