### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dongyy1148** [govvijaycal/mkz_mpc_path_follower#2]
Hi,

I just start to install your package. There are only two steps in the tutorial. However, when I input 
`sudo apt-get install ros-$ROS_DISTRO-dbw-mkz-simulator`
It returns 
`E: Unable to locate package ros-kinetic-dbw-mkz-simulator`
Could you help fix this our? I use ros kinetic and Gazebo 7. Thanks!

**Comment by govvijaycal** [comment]
Did you try the install steps on this page first:
https://bitbucket.org/DataspeedInc/dbw_mkz_simulation/src/default/

They may have changed things since I started so start with their up to date
instructions first.

**Comment by dongyy1148** [comment]
Yep. I exactly use the twp steps installation showed on that website.

**Comment by govvijaycal** [comment]
Hmm it seems they’ve updated to a second version:
https://bitbucket.org/DataspeedInc/dataspeed_dbw_simulation/src/master/

If that guide doesn’t help, you should contact Dataspeed with information
on the steps you tried and the error message you get.

**Comment by dongyy1148** [comment]
@govvijaycal Thanks a lot for your help! I will try this later.
